develop:
    version: 1.0.0 Asynchronous # The version. This only influences the develop.about command.
    operators: # A list, now reserved, will be useful in the future
osubot:
    key: # Your osu! api key
